version: "3.8"
services:
  postgres-db:
    container_name: easel-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 5s
      retries: 30

  backend:
    container_name: easel-api
    build:
      context: ./backend
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
        rails_master_key: ${RAILS_MASTER_KEY}
    volumes:
      - ./backend:/backend:cached
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      - DATABASE_HOST=postgres-db
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db/
    depends_on:
      postgres-db:
        condition: service_healthy
    env_file:
      - ./backend/.env

  frontend:
    container_name: easel-web
    build: ./frontend
    volumes:
      - ./frontend:/frontend:cached
      - nuxt_node_modules:/frontend/node_modules
    ports:
      - "3030:3030"
      - "24678:24678"
    tty: true
    stdin_open: true
    environment:
      - HOST=0.0.0.0
      - port=3030
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env
    command: sh -c "pnpm dev"

volumes:
  nuxt_node_modules:

